"""Metadata filter validation tests.

Tests are organized into 6 phases:
  Phase 1: Metadata injection integrity (ingestion layer)
  Phase 2: Pre-filter isolation correctness (retrieval layer)
  Phase 3: Semantic penetration tests
  Phase 4: Recall completeness
  Phase 5: Edge cases
  Phase 6: Q5 regression test (original motivation for metadata filtering)

Pipeline rebuild strategy:
  - If Qdrant VectorStore exists and is consistent with results.json → skip rebuild
  - Otherwise → clean + rebuild automatically
"""

import logging
from pathlib import Path
from typing import Any, Sequence

import pytest
from llama_index.core.schema import BaseNode, NodeWithScore

from app.configs.rag_config import WEBPAGES_DATA_FOLDER_PATH
from app.modules.rag import Rag

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────
RESULTS_JSON_PATH = Path(WEBPAGES_DATA_FOLDER_PATH) / "results.json"
QDRANT_DB_PATH = (
    Path(WEBPAGES_DATA_FOLDER_PATH) / ".." / "rag" / "results" / "qdrant_db"
)

# Map of page_title → expected page_type (sampled from results.json)
# Generated by crawling results — update when crawler URL→page_type mapping changes.
EXPECTED_PAGE_TYPES: dict[str, str] = {
    "Web Intelligence and Data Mining Lab": "general",
    "Advisor": "general",  # /advisor not mapped to personnel in current crawler
    "校內奬項": "announcement",
    "Publication": "paper",
    "Publication by Year": "paper",
    "Thesis Advised": "paper",
    "Members": "personnel",
    "Activities": "personnel",
    "Join WIDM": "personnel",
    "Letter to potential students": "personnel",
}

# Pages expected to have date metadata under specific strategies
PAGES_WITH_HEADING_YEAR = {"Publication by Year"}
PAGES_WITH_POST_DATE = {"UWIDE2"}
PAGES_WITH_TRAILING_DATE = {"校內奬項"}
PAGES_WITH_FALLBACK_YEAR = {"Publication by Year"}
PAGES_WITHOUT_DATE = {"Web Intelligence and Data Mining Lab"}


# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────


def _has_existing_qdrant_db() -> bool:
    """Check if Qdrant storage directory exists and is non-empty."""
    return QDRANT_DB_PATH.exists() and any(QDRANT_DB_PATH.iterdir())


def _set_logging() -> None:
    """Enable debug logging for test diagnostics."""
    logging.basicConfig(level=logging.DEBUG)


def _get_nodes_by_page_title(
    nodes: Sequence[BaseNode] | None, title: str
) -> list[BaseNode]:
    """Filter nodes by page_title metadata."""
    if nodes is None:
        return []
    return [n for n in nodes if n.metadata.get("page_title") == title]


def _assert_all_nodes_match_filter(
    source_nodes: list[NodeWithScore],
    key: str,
    expected_value: Any,
) -> None:
    """Assert all returned nodes have the expected metadata value.

    This is the CORE assertion pattern for all filter isolation tests.
    """
    for node in source_nodes:
        actual = node.node.metadata.get(key)
        assert actual == expected_value, (
            f"Filter leak detected: node from "
            f"'{node.node.metadata.get('page_title', '?')}' "
            f"has {key}={actual!r}, expected {expected_value!r}"
        )


# ──────────────────────────────────────────────────────────────────────
# Fixtures
# ──────────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def rag() -> Rag:
    """Provide a Rag instance with fully rebuilt nodes, vector store, and index.

    Always rebuilds from scratch to guarantee metadata injection integrity.
    The existing Qdrant DB (if any) was built before metadata fields existed,
    so loading it would lose ``page_type``/``year``/``description`` metadata.
    """
    _set_logging()
    instance = Rag()

    if _has_existing_qdrant_db():
        logger.info(
            "Cleaning stale Qdrant DB (pre-dates metadata injection) — rebuilding"
        )
        instance.clean_vector_store()

    instance.build_nodes()
    instance.build_vector_store()
    instance.build_index()

    return instance


# ──────────────────────────────────────────────────────────────────────
# Phase 1: Metadata Injection Integrity (Ingestion Layer)
# ──────────────────────────────────────────────────────────────────────


class TestMetadataInjection:
    """Verify that build_nodes() correctly injects metadata from results.json."""

    def test_page_type_propagation(self, rag: Rag) -> None:
        """Every node must carry a valid page_type matching its source page."""
        for page_title, expected_ptype in EXPECTED_PAGE_TYPES.items():
            matching = _get_nodes_by_page_title(rag.nodes, page_title)
            assert matching, f"No nodes found for page '{page_title}'"
            for node in matching:
                actual = node.metadata.get("page_type")
                assert actual == expected_ptype, (
                    f"Node from '{page_title}' has page_type={actual!r}, "
                    f"expected {expected_ptype!r}"
                )

    def test_date_extraction_heading_year(self, rag: Rag) -> None:
        """Strategy 1: Section heading (### 2026) should set year."""
        for page_title in PAGES_WITH_HEADING_YEAR:
            nodes = _get_nodes_by_page_title(rag.nodes, page_title)
            nodes_with_year = [n for n in nodes if n.metadata.get("year") is not None]
            assert nodes_with_year, (
                f"No nodes from '{page_title}' have year metadata "
                f"— heading year strategy may have failed"
            )
            for n in nodes_with_year:
                assert isinstance(n.metadata["year"], int), (
                    f"year metadata should be int, got {type(n.metadata['year'])}"
                )
                assert isinstance(n.metadata["year"], int), (
                    f"year metadata should be int, got {type(n.metadata['year'])}"
                )

    def test_date_extraction_post_date(self, rag: Rag) -> None:
        """Strategy 2: Post date line should set year/month/day."""
        for page_title in PAGES_WITH_POST_DATE:
            nodes = _get_nodes_by_page_title(rag.nodes, page_title)
            dated = [n for n in nodes if n.metadata.get("year") is not None]
            assert dated, f"No nodes from '{page_title}' have date metadata"
            sample = dated[0]
            assert isinstance(sample.metadata.get("year"), int)
            assert isinstance(sample.metadata.get("month"), int)
            assert isinstance(sample.metadata.get("day"), int)
            logger.info(
                f"Post date test: '{page_title}' → year={sample.metadata['year']}, "
                f"month={sample.metadata['month']}, day={sample.metadata['day']}"
            )

    def test_date_extraction_trailing_date(self, rag: Rag) -> None:
        """Strategy 3: Trailing date (— Mon. DD, YYYY) should set year/month/day."""
        for page_title in PAGES_WITH_TRAILING_DATE:
            nodes = _get_nodes_by_page_title(rag.nodes, page_title)
            dated = [n for n in nodes if n.metadata.get("year") is not None]
            assert dated, f"No nodes from '{page_title}' have date metadata"
            sample = dated[0]
            assert isinstance(sample.metadata.get("year"), int)
            assert isinstance(sample.metadata.get("month"), int)
            assert isinstance(sample.metadata.get("day"), int)

    def test_date_extraction_no_date_pages(self, rag: Rag) -> None:
        """Pages without date clues should NOT have year metadata."""
        for page_title in PAGES_WITHOUT_DATE:
            nodes = _get_nodes_by_page_title(rag.nodes, page_title)
            dated = [n for n in nodes if n.metadata.get("year") is not None]
            if dated:
                # This may happen if fallback strategy (4) is too aggressive.
                # Log a warning rather than failing — inspect manually.
                logger.warning(
                    f"Page '{page_title}' unexpectedly has year metadata"
                    f" on {len(dated)}/{len(nodes)} nodes"
                )

    def test_description_integrity(self, rag: Rag) -> None:
        """All nodes should have a non-empty description (from results.json)."""
        if rag.nodes is None:
            pytest.skip("No nodes loaded — cannot test description integrity")
        empty_desc = [
            n for n in rag.nodes if not (n.metadata.get("description") or "").strip()
        ]
        if empty_desc:
            titles = set(n.metadata.get("page_title", "?") for n in empty_desc)
            logger.warning(
                f"{len(empty_desc)} nodes from {titles} have empty description"
            )


# ──────────────────────────────────────────────────────────────────────
# Phase 2: Pre-filter Isolation Correctness (Retrieval Layer)
# ──────────────────────────────────────────────────────────────────────


class TestFilterIsolation:
    """Verify that pre-filter correctly restricts results by metadata."""

    @pytest.mark.parametrize(
        "page_type", ["personnel", "announcement", "paper", "general"]
    )
    def test_single_filter_page_type(self, rag: Rag, page_type: str) -> None:
        """All retrieved nodes must match the requested page_type."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": page_type})
        rag.build_query_engine()
        response = rag.query(page_type)  # use the page type as a simple query
        _assert_all_nodes_match_filter(response.source_nodes, "page_type", page_type)
        logger.info(
            f"page_type={page_type}: {len(response.source_nodes)} nodes returned, "
            f"all with correct page_type"
        )

    def test_single_filter_year(self, rag: Rag) -> None:
        """All retrieved nodes must match the requested year."""
        test_year = 2024
        rag.build_retriever(top_k=20, filter_dict={"year": test_year})
        rag.build_query_engine()
        response = rag.query("publication paper")
        _assert_all_nodes_match_filter(response.source_nodes, "year", test_year)

    def test_multi_filter_combination(self, rag: Rag) -> None:
        """Combined page_type + year filter must satisfy both constraints."""
        rag.build_retriever(
            top_k=20,
            filter_dict={"page_type": "paper", "year": 2025},
        )
        rag.build_query_engine()
        response = rag.query("transformer attention")
        for node in response.source_nodes:
            assert node.node.metadata.get("page_type") == "paper"
            assert node.node.metadata.get("year") == 2025


# ──────────────────────────────────────────────────────────────────────
# Phase 3: Semantic Penetration Tests
# ──────────────────────────────────────────────────────────────────────


class TestFilterPenetration:
    """Verify that pre-filter isolates by metadata, NOT by content similarity.

    The key insight: these tests assert metadata correctness, NOT empty results.
    Announcement pages may contain paper-related keywords (e.g., award notices
    congratulating a paper acceptance). Non-empty results with correct metadata
    are valid — empty results would be a bonus but not required.
    """

    def test_announcement_isolation(self, rag: Rag) -> None:
        """Paper-related query under announcement filter must not leak paper nodes."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": "announcement"})
        rag.build_query_engine()
        response = rag.query("transformer attention BERT deep learning")
        _assert_all_nodes_match_filter(
            response.source_nodes, "page_type", "announcement"
        )

    def test_paper_isolation_reverse(self, rag: Rag) -> None:
        """Award-related query under paper filter must not leak announcement nodes."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": "paper"})
        rag.build_query_engine()
        response = rag.query("校內奬項 賀 獲獎 第一名")
        _assert_all_nodes_match_filter(response.source_nodes, "page_type", "paper")


# ──────────────────────────────────────────────────────────────────────
# Phase 4: Recall Completeness
# ──────────────────────────────────────────────────────────────────────


class TestRecallCompleteness:
    """Verify that with correct filter + query, the system retrieves what it should."""

    def test_paper_recall(self, rag: Rag) -> None:
        """Paper filter must include the main publication pages."""
        rag.build_retriever(top_k=30, filter_dict={"page_type": "paper"})
        rag.build_query_engine(cutoff=0.0)  # disable cutoff to avoid filtering nodes
        response = rag.query("論文 發表 journal conference thesis PhD 碩博士論文")
        returned_titles = {
            n.node.metadata.get("page_title", "") for n in response.source_nodes
        }
        expected = {"Publication", "Publication by Year", "Thesis Advised"}
        missing = expected - returned_titles
        assert not missing, (
            f"Paper recall failure — missing pages: {missing}. "
            f"Returned: {returned_titles}"
        )

    def test_personnel_recall(self, rag: Rag) -> None:
        """Personnel filter must return nodes from personnel pages."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": "personnel"})
        rag.build_query_engine()
        response = rag.query("成員 學生 教授 指導教授")
        returned_titles = {
            n.node.metadata.get("page_title", "") for n in response.source_nodes
        }
        # Advisor is currently classified as general, not personnel.
        # Verify at least one known personnel page is retrieved.
        personnel_pages = {
            "Members",
            "Activities",
            "Join WIDM",
            "Letter to potential students",
        }
        hit = returned_titles & personnel_pages
        assert hit, (
            f"Personnel recall failure — no known personnel page found. "
            f"Returned: {returned_titles}"
        )


# ──────────────────────────────────────────────────────────────────────
# Phase 5: Edge Cases
# ──────────────────────────────────────────────────────────────────────


class TestEdgeCases:
    """Verify graceful handling of boundary conditions."""

    def test_nonexistent_page_type(self, rag: Rag) -> None:
        """A filter value that matches nothing should return 0 results."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": "nonexistent"})
        rag.build_query_engine()
        response = rag.query("anything")
        assert len(response.source_nodes) == 0, (
            f"Expected 0 results for nonexistent filter, "
            f"got {len(response.source_nodes)}"
        )

    def test_empty_filter_dict(self, rag: Rag) -> None:
        """None filter should degrade gracefully to unfiltered retrieval."""
        rag.build_retriever(top_k=5, filter_dict=None)
        rag.build_query_engine()
        response = rag.query("張嘉惠 教授 機器學習 深度學習")
        assert len(response.source_nodes) > 0, (
            "None filter should return results (degrade to no filter)"
        )
        assert len(response.source_nodes) <= 5, (
            f"top_k=5 should limit results, got {len(response.source_nodes)}"
        )


# ──────────────────────────────────────────────────────────────────────
# Phase 6: Q5 Regression Test
# ──────────────────────────────────────────────────────────────────────


class TestRegression:
    """Regression tests for known failures.

    Q5 (from rag_cutoff04_topk10_eval.md) failed because award/announcement
    pages were mixed into paper query results. Metadata filter should fix this.
    """

    def test_q5_paper_query_no_leakage(self, rag: Rag) -> None:
        """Q5 fix: paper-filtered query must not retrieve non-paper nodes."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": "paper"})
        rag.build_query_engine(cutoff=0.0)
        response = rag.query("實驗室近三年發表過哪些論文？", log_sources=True)

        # Assertion 1: No leakage — all nodes must be paper type
        _assert_all_nodes_match_filter(response.source_nodes, "page_type", "paper")

        # Assertion 2: Recall — publication pages must be present
        returned_titles = {
            n.node.metadata.get("page_title", "") for n in response.source_nodes
        }
        assert any("Publication" in t for t in returned_titles), (
            f"No publication pages retrieved — recall failure. "
            f"Returned: {returned_titles}"
        )

    def test_q5_paper_query_relevancy(self, rag: Rag) -> None:
        """Q5 fix: paper-filtered query should pass relevancy evaluation."""
        rag.build_retriever(top_k=20, filter_dict={"page_type": "paper"})
        rag.build_query_engine(cutoff=0.0)
        response = rag.query("實驗室近三年發表過哪些論文？")

        faithfulness_result, relevancy_result = rag.evaluate(
            "實驗室近三年發表過哪些論文？", response
        )
        assert relevancy_result.passing, (
            f"Q5 regression: Relevancy still failing after metadata filter. "
            f"Details: {relevancy_result.feedback}"
        )
