[init]
webpages_data_folder_path = "data/webpages"

[vector_store]
milvus_uri = "data/rag/results/milvus_dense_q4.db"
vector_store_type = "milvus"
qdrant_db_folder_path = "data/rag/results/qdrant_db"
hybrid_ranker = "WeightedRanker"
collection_name = "webpages"

[nodes]
chunk_overlap = 100
paragraph_separator = "\n\n"
chunk_size = 800

[index]
embedding_name = "text-embedding-3-small"

[retriever]
alpha = 0.5
query_mode = "default" # run name
hybrid_top_k = 10
similarity_top_k = 10

[query_engine]
cutoff = 0.4
llm_name = "gemini-3.1-flash-lite"
query = "如何聯絡研究室指導教授？"
