[project]
name = "website-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "crawl4ai>=0.8.0",
    "langchain-community>=0.4.1",
    "litellm>=1.0.0",
    "playwright>=1.58.0",
    "pyright>=1.1.408",
    "python-dotenv>=1.0.0",
]

[tool.ruff]
exclude = [
    "dev/**",
    ".venv",
]
[tool.pyright]
exclude = [
    "dev/**", 
    "**/node_modules", 
    "**/__pycache__", 
    ".venv",
    "**/.*", 
]
[tool.pytest.ini_options]
pythonpath = ["."]
log_cli = true
log_cli_level = "INFO"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.4",
]
