[init]
webpages_data_folder_path = "data/webpages"

[nodes]
chunk_size = 800
chunk_overlap = 100
paragraph_separator = "\n\n"

[vector_store]
vector_store_type = "qdrant"
qdrant_db_folder_path = "data/rag/results/qdrant_db"
collection_name = "webpages"

[index]
embedding_name = "text-embedding-3-small"

[retriever]
query_mode = "hybrid" # run name
similarity_top_k = 10
hybrid_top_k = 10
alpha = 0.5

[query_engine]
query_llm_name = "gemini-3.1-flash-lite"
evaluator_llm_name = "gpt-5.4"
cutoff = 0.4
query = "實驗室的成員有哪些人？"
