name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run lint
        run: |
          uv run ruff check .

      - name: Run type check
        run: uv run pyright .
  unit-test:
    needs: quality-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Install Playwright browsers
        run: |
          uv run playwright install-deps
          uv run playwright install

      - name: Set up environment variables
        run:  |
          echo "OPENAI_WEBPAGE_IMAGE_SUMMARIZER_VLM_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "GEMINI_WEBPAGE_IMAGE_SUMMARIZER_VLM_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "OPENAI_RAG_EMBEDDING_API_KEY"=${{ secrets.OPENAI_API_KEY }} >> .env
          echo "GEMINI_RAG_QUERY_ENGINE_API_KEY"=${{ secrets.GEMINI_API_KEY }} >> .env

      - name: Run tests
        run: uv run pytest src/test/test_module.py
